### ISSUE TITLE
macos support

### ISSUE THREAD

**Issue by shahabqamar** [tom-mohr/particle-life-app#3]
Hi, thank you for making this awesome program!

I would like to know if there is a way to run this program on macos. 

Cheers

**Comment by tom-mohr** [comment]
Hi, thank you! Currently not. It's theoretically possible, it only requires some configuration of the build process. But I don't have a Mac, so the only chance for this to happen is if someone else does it. I will gladly merge any pull request that provides support for MacOS. It seems like there will be Linux support soon, so maybe MacOS isn't too far away.
Greetings

**Comment by shahabqamar** [comment]
Got it. Just had a quick look at the pull request for linux support. 

It appears to check for macos:  
#4 
https://github.com/tom-mohr/particle-life-app/pull/4/commits/d7941f7ff7b5eb4a6d1eb0df287c20f11cd3e386#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R73

I tested updated my local build.gradle file to see if it works on macos but still throwing errors: 

```
> Task :run FAILED
Using LWJGL 3.3.0 3.3.0
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1046)
        at com.particle_life.app.App.init(App.java:102)
        at com.particle_life.app.App.launch(App.java:39)
        at com.particle_life.app.Main.main(Main.java:38)
Caused by: java.lang.IllegalStateException: GLFW may only be used on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.
        at org.lwjgl.glfw.EventLoop.<clinit>(EventLoop.java:30)
        ... 4 more
```

**Comment by moob10293** [comment]
have you tried running the JVM with -XstartOnFirstThread?

**Comment by vtnil** [comment]
I have been running on Mac m1 successful. The main problem base on the two library `lwjgl` and `imgui`. 
You can edit the `build.gradle` file like this:

```
 ...

 10
 11 application {
 12     mainClass = "com.particle_life.app.Main"  // required for "run" task
 13
 14     if (OperatingSystem.current() == OperatingSystem.MAC_OS) {
 15         applicationDefaultJvmArgs = ["-XstartOnFirstThread",'-Djava.awt.headless=true']
 16     }
 17     try {
 18         if (libPath) {
 19             applicationDefaultJvmArgs += ["-Dimgui.library.path=$libPath"]
 20         }
 21     } catch (ignored) {
 22         // ignore
 23     }
 24 }
 25

...

110     processResources.exclude('*')
111 }
112
113 // project.ext.lwjglVersion = "3.3.0"
114 project.ext.lwjglVersion = "3.3.0-SNAPSHOT"
115 project.ext.lwjglNatives = "natives-macos-arm64"
116
117 switch (OperatingSystem.current()) {
118     case OperatingSystem.LINUX:

...

158     implementation "com.github.tom-ski.imgui-java:imgui-java-app:v1.86.2"
159
160     // LWJGL
161     // see https://www.lwjgl.org/customize for a list of all available contents
162 //    [".lwjgl", ".glfw", ".opengl"].each {
163 //        implementation "org.lwjgl.osgi:org.lwjgl$it:$lwjglVersion"
164 //    }
165
166     implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
167     implementation "org.lwjgl:lwjgl"
168     implementation "org.lwjgl:lwjgl-glfw"
169     implementation "org.lwjgl:lwjgl-opengl"
170     runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
171     runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
172     runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"
```

Then compile `imgui-java` for M1 from this repo: https://github.com/Tom-Ski/imgui-java

Finally, run code with your local `imgui-java` like this:

```
./gradlew run -PlibPath=../imgui-java/imgui-binding/build/libsNative/macosxarm64
```

have fun~

**Comment by tom-mohr** [comment]
Awesome! Could you imagine turning this into a pull request? This would require automating this in the `build.gradle` so that M1 users don't have to compile `imgui-java` by hand and don't need to explicitly specify the `-PlibPath` argument. They should just be able to do `./gradlew run`.
And if someone else is reading this, feel free to do this and create a PR!!
I think it would be very appreciated by M1 users.

**Comment by falkon2** [comment]
Any Update on this?
